project:
  type: website
  output-dir: docs
website:
  title: "Pankaj Chejara"
  navbar:
    left:
      - Blog.md
      - Projects.md
      - Awards.md
      - cv.qmd
    right:
      - icon: twitter
        href: https://twitter.com/pankajchejara1
      - icon: linkedin
        href: https://www.linkedin.com/in/pankaj-chejara-5ab77855/
      - icon: github
        href: https://github.com/pankajchejara23
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true
format:
  html:
    theme: flatly
    css: styles.css




